### ISSUE TITLE
支持支持！能一键部署vercel吗？

### ISSUE THREAD

**Issue by Flyingpen** [weaigc/bingo#1]
支持支持！能一键部署vercel吗？
从go-proxy-bingai过来的，力挺作者延续了这个作品！

**Comment by weaigc** [comment]
@Flyingpen [一键部署](https://vercel.com/new/clone?demo-title=bingo&demo-description=bingo&demo-url=https%3A%2F%2Fbing.github1s.tk%2F&project-name=bingo&repository-name=bingo&repository-url=https%3A%2F%2Fgithub.com%2Fweaigc%2Fbingo&from=templates&skippable-integrations=1&env=BING_COOKIE%2CBING_UA%2CBING_IP) 。Vercel 免费版是没办法跑通的，因为 /api/sydney 请求会超过 10s，而免费版的 Vercel 不支持超过10s的请求

**Comment by Mchousexuxu** [comment]
大佬 我在vercel部署的 专业版，部署完成后 只有第一个问题可以回答,可以帮忙看下吗
![image](https://github.com/weaigc/bingo/assets/133076068/db2b48b6-6726-450a-bc21-801acfb3452a)
