### ISSUE TITLE
我已经正确填写了我的用户信息，可是仍然提示“没有获取到身份信息或身份信息失效，点此重新设置”，要怎么处理？

### ISSUE THREAD

**Issue by FangZirui-E5** [weaigc/bingo#10]
![image](https://github.com/weaigc/bingo/assets/129593198/d67b19b0-4847-4657-b132-afc679e8618c)
![image](https://github.com/weaigc/bingo/assets/129593198/973042cb-0d98-4cd5-9bdf-5925aabe748e)

**Comment by ysmzxc** [comment]
我也遇到了一样的问题，使用的是自己部署的还是作者的第二个link

**Comment by weaigc** [comment]
@FangZirui-E5 @ysmzxc cookie需要从 www.bing.com 获取（这个需要翻墙）

**Comment by weaigc** [comment]
我更新一下README

**Comment by lwdgit** [comment]
@ysmzxc @FangZirui-E5 上线了新的认证方式 https://github.com/weaigc/bingo#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%20BING_HEADER

**Comment by weaigc** [comment]
@ysmzxc @FangZirui-E5 换了一种认证方式，再试试？

**Comment by FangZirui-E5** [comment]
> @ysmzxc @FangZirui-E5 换了一种认证方式，再试试？

这个是什么意思？（没太明白“再试试”是指什么）

**Comment by nence1** [comment]
大佬，为什么你的第一个站点不需要cookie验证，是怎么弄的 @weaigc

**Comment by FangZirui-E5** [comment]
> @ysmzxc @FangZirui-E5 换了一种认证方式，再试试？

这个BING_HEADER是永久有效的还是需要定时更新的？

**Comment by weaigc** [comment]
> > @ysmzxc @FangZirui-E5 换了一种认证方式，再试试？
> 
> 这个BING_HEADER是永久有效的还是需要定时更新的？

@FangZirui-E5 账号没有被封杀的话就可以用很久，具体多久还没有测
