### ISSUE TITLE
api POST多轮对话失败!!!!!!!

### ISSUE THREAD

**Issue by LizFun** [weaigc/bingo#116]
body字段按照OpenAI提供的messages方法，成员依次：system → user → assistant → user，可是输出的内容是已经出现过的assistant内容

**Comment by weaigc** [comment]
> body字段按照OpenAI提供的messages方法，成员依次：system → user → assistant → user，可是输出的内容是已经出现过的assistant内容

bing的message是一个特殊的构造，跟openai不一样，你可以参考这个https://github.com/weaigc/bingo/blob/eaebba306d5f68b940e4486ad81897516d0db0f3/src/lib/utils.ts#L43
