### ISSUE TITLE
我在用新代码进行vercel部署之后使用时出现了人机验证

### ISSUE THREAD

**Issue by FangZirui-E5** [weaigc/bingo#12]
![image](https://github.com/weaigc/bingo/assets/129593198/313af544-486a-465d-934c-c3488f92b81a)
![image](https://github.com/weaigc/bingo/assets/129593198/21b97fec-1f22-4fd0-aa88-3b398047df46)
![image](https://github.com/weaigc/bingo/assets/129593198/816d29dd-56a8-4b7e-9c04-19ac714490c4)

**Comment by FangZirui-E5** [comment]
测试科学上网之后可以通过人机验证，但是通过之后会继续叫我进行人机验证，不放通聊天

**Comment by weaigc** [comment]
> 

@FangZirui-E5 站点可以发我一下吗，我试试

**Comment by FangZirui-E5** [comment]
> > 
> 
> @FangZirui-E5 站点可以发我一下吗，我试试

https://bing2.smallfang.us

**Comment by weaigc** [comment]
> > > 
> > 
> > 
> > @FangZirui-E5 站点可以发我一下吗，我试试
> 
> https://bing2.smallfang.us
@FangZirui-E5 
估计是这个节点被封锁了，暂时无解，推荐使用 hf 部署，文档我更新了一下。

**Comment by FangZirui-E5** [comment]
![image](https://github.com/weaigc/bingo/assets/129593198/8bd4233c-befb-418c-b223-6f131ba4feb9)
hugging face的情况也不妙😥

**Comment by weaigc** [comment]
> ![image](https://user-images.githubusercontent.com/129593198/257382743-8bd4233c-befb-418c-b223-6f131ba4feb9.png) hugging face的情况也不妙😥
@FangZirui-E5 看起来没啥问题
![image](https://github.com/weaigc/bingo/assets/39235693/1ea67de1-661d-4670-9bd4-cad1d90c1683)

**Comment by FangZirui-E5** [comment]
呃

现在情况又变了
![image](https://github.com/weaigc/bingo/assets/129593198/2580eb9b-a69d-402b-b9b4-99f2124b11f5)

**Comment by weaigc** [comment]
> 呃
> 
> 现在情况又变了 ![image](https://user-images.githubusercontent.com/129593198/257728382-2580eb9b-a69d-402b-b9b4-99f2124b11f5.png)
@FangZirui-E5 
你先清除设置看看，不设置用户信息

**Comment by FangZirui-E5** [comment]
我在前端的UI页面上没有填写过，我是在后台填了一个环境变量，意思是这个环境变量也要去掉吗

**Comment by weaigc** [comment]
@FangZirui-E5 推荐使用 hf 哈，vercel 确实会出现问题。README我更新了一下，你可以参考着来。

**Comment by FangZirui-E5** [comment]
> @FangZirui-E5 推荐使用 hf 哈，vercel 确实会出现问题。README我更新了一下，你可以参考着来。

可以用了，谢谢Thanks♪(･ω･)ﾉ
