### ISSUE TITLE
设置了个人信息，绘图基本都是用代码画的，而不是生成的AI图片

### ISSUE THREAD

**Issue by costaq** [weaigc/bingo#127]
设置了个人信息，选了创造力，试了好多次，只有一次是帮我画了4张图片，其他的时候都是这样
![image](https://github.com/weaigc/bingo/assets/24690993/8f3c19de-ea28-48e2-8592-91b42450e00e)
这是什么原因？
![image](https://github.com/weaigc/bingo/assets/24690993/db9968ab-bc6e-42a2-b635-2a5e2a2ae352)

**Comment by wuyuncheng-26** [comment]
同 #121

**Comment by coccvo** [comment]
上传图片，以及让ai画图，都得关闭gpt4模式

**Comment by Mriew** [comment]
> 上传图片，以及让ai画图，都得关闭gpt4模式

成功了 感谢解答
