### ISSUE TITLE
部署的几个问题

### ISSUE THREAD

**Issue by bullkq** [weaigc/bingo#15]
1 render一键部署时，我用github账号进入render，但自动就登出了，不知道为啥，改用谷歌账号登录后关联github账号由说id被占用。
2 netlify可以部署，但是经常出现unknow errors
3 在部署后的界面里，设置用户时点击登录这个链接https://www.bing.com/turing/captcha/challenge 
但是自动跳转为https://cn.bing.com/turing/captcha/challenge ，提示无效域
https://www.bing.com/turing/conversation/create 这个链接打不开，不知道如何

问题3进展，我通过微软虚拟机https://learn.microsoft.com/zh-cn/training/modules/implement-common-integration-features-finance-ops/10-exercise-1
登录edge后，可以进入www.bing.com并且获得了create的链接。回到部署界面用户设置后，页面说保存成功并且似乎重新刷新了一下，但是提问时显示你已达到每日最大发送消息次数，请[更换账号]或隔一天后重试

4 这个貌似不能切换平衡模式和精确模式，只有创造模式吗

5 https://bing.github1s.tk/ 这个貌似使用正常，是怎么弄得，教教我呗

**Comment by weaigc** [comment]
@bullkq 目前测下来就 hf 的比较稳定，其它的平台都有阻断，我在readme里面详细介绍一下hf怎么部署
