### ISSUE TITLE
HF 部署的环境变量问题

### ISSUE THREAD

**Issue by ghost** [weaigc/bingo#23]
HF 部署时需要填一个 IMAGE_BING_COOKIE ，描述是 Cookie _U 值。我把自己账号的 _U 复制进去了，但是好像并没有生效？还是说这个 IMAGE_BING_COOKIE 应该填 BING_HEADER？

**Comment by weaigc** [comment]
> HF 部署时需要填一个 IMAGE_BING_COOKIE ，描述是 Cookie _U 值。我把自己账号的 _U 复制进去了，但是好像并没有生效？还是说这个 IMAGE_BING_COOKIE 应该填 BING_HEADER？

@Cyrus-Reed 不生效是指？IMAGE_BING_COOKIE 是只用 _U 值画图，不同步历史记录，如果需要历史记录，则需要 BING_HEADER，新版有优先，你更新一下
