### ISSUE TITLE
无效域。如果此问题仍然存在，请与站点管理员联系。

### ISSUE THREAD

**Issue by jj-lgtm** [weaigc/bingo#27]
打开https://[cn.bing.com/turing/captcha/challenge](https://cn.bing.com/turing/captcha/challenge)后显示“无效域。如果此问题仍然存在，请与站点管理员联系。”我应该怎么办？
![image](https://github.com/weaigc/bingo/assets/110281478/5719d2c6-592f-4cce-b749-29c32ad0824b)

**Comment by weaigc** [comment]
> 打开https://[cn.bing.com/turing/captcha/challenge](https://cn.bing.com/turing/captcha/challenge)后显示“无效域。如果此问题仍然存在，请与站点管理员联系。”我应该怎么办？ ![image](https://user-images.githubusercontent.com/110281478/260642610-5719d2c6-592f-4cce-b749-29c32ad0824b.png)

@jj-lgtm 更新最新代码，忽略页面提示，直接操作

**Comment by jj-lgtm** [comment]
你好，它会提示格式不正确
![image](https://github.com/weaigc/bingo/assets/110281478/d1db31b7-34b9-4d2e-af8c-4843c67d8fcb)

**Comment by weaigc** [comment]
> 你好，它会提示格式不正确 ![image](https://user-images.githubusercontent.com/110281478/261862774-d1db31b7-34b9-4d2e-af8c-4843c67d8fcb.png)

你更新一下空间，最新代码才支持。你可以在这里试试 https://bing.github1s.tk/
