### ISSUE TITLE
提问时，总是遭遇UnauthorizedRequest报错，导致无法提问

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#28]
能不能修复提问的过程中，总是报UnauthorizedRequest的问题？无论什么时候提问，都会显示图片中的情况，如果能修复好，我会非常感谢！
![Screenshot_20230815_172146](https://github.com/weaigc/bingo/assets/129951996/f138ac78-4c57-4ff3-829f-dfe9660c1537)

**Comment by weaigc** [comment]
@player868 你的账号应该是有问题了，更新一下新版试试

**Comment by KWidLuK** [comment]
> @player868 你的账号应该是有问题了，更新一下新版试试

我也遇到相同的问题，请问怎么更新？

**Comment by weaigc** [comment]
@player868 @KWidLuK https://github.com/weaigc/bingo/issues/32 参考这里
