### ISSUE TITLE
请求实现快捷复制答案等功能

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#29]
能考虑下把图片中的功能，加入至其中吗？拖拽复制答案可能会非常麻烦，但是我认为一键复制答案的功能，可能会更加方便。如果可以，我将会非常感谢！
![Screenshot_20230815_171908](https://github.com/weaigc/bingo/assets/129951996/de0a354a-8814-4cd6-9ccc-caa24f38d366)

**Comment by weaigc** [comment]
好的

**Comment by weaigc** [comment]
@player868 done
