### ISSUE TITLE
请问是否支持其他托管平台？

### ISSUE THREAD

**Issue by 1iang** [weaigc/bingo#3]
在zeabur上部署成功，也配置了BING_COOKIE、BING_IP、BING_UA三个环境变量，但没法回答。
![1690341372822](https://github.com/weaigc/bingo/assets/49504005/1b74ed81-e90c-411d-835a-872bcab20ec9)

**Comment by weaigc** [comment]
> 在zeabur上部署成功，也配置了BING_COOKIE、BING_IP、BING_UA三个环境变量，但没法回答。 ![1690341372822](https://user-images.githubusercontent.com/49504005/256104255-1b74ed81-e90c-411d-835a-872bcab20ec9.png)

@1iang 支持的，不行的话你可能需要改一下 BING_IP。另外注意一下 BING_COOKIE 和 BING_UA 是要对得上的，不能随便写
