### ISSUE TITLE
“没有获取到身份信息或身份信息失效，点此重新设置”报错

### ISSUE THREAD

**Issue by 2043356647** [weaigc/bingo#31]
在本地使用node部署后，不设置用户信息，询问会显示“没有获取到身份信息或身份信息失效，点此重新设置”
![屏幕截图 2023-08-16 172229](https://github.com/weaigc/bingo/assets/61368281/0b27e97b-b9a2-47ee-95b1-9f5603f17a80)
![屏幕截图 2023-08-16 172241](https://github.com/weaigc/bingo/assets/61368281/fb4f1e1f-f7f7-4d9c-98b2-c9de660af832)

**Comment by weaigc** [comment]
> 在本地使用node部署后，不设置用户信息，询问会显示“没有获取到身份信息或身份信息失效，点此重新设置” ![屏幕截图 2023-08-16 172229](https://user-images.githubusercontent.com/61368281/260964220-0b27e97b-b9a2-47ee-95b1-9f5603f17a80.png) ![屏幕截图 2023-08-16 172241](https://user-images.githubusercontent.com/61368281/260964224-fb4f1e1f-f7f7-4d9c-98b2-c9de660af832.png)

@2043356647 由于目前微软封杀比较严重，推荐优先使用部署 Huggingfaceuggingface
