### ISSUE TITLE
如果作者的代码更新里，我部署的HF还需要重新部署吗

### ISSUE THREAD

**Issue by willggy** [weaigc/bingo#34]
如题，还有就是可以把header写死吗 别人访问的时候不用填，谢谢作者

**Comment by willggy** [comment]
把header复制过去后出现vps已被禁

**Comment by weaigc** [comment]
@willggy 你可以像同步github一样在本地同步huggingface代码，不过这样比较麻烦，建议你直接删除空间重新部署
