### ISSUE TITLE
HF 部署后 使用过程中经常报错

### ISSUE THREAD

**Issue by Cyrus-Reed** [weaigc/bingo#36]
发送问题后会提示：你的 VPS 或代理可能被封禁，如有疑问，请前往 https://github.com/weaigc/bingo 咨询

刷新一下就又能用了，但是不稳定，随时可能会再次出现。

**Comment by willggy** [comment]
我这刷新也不管用，

**Comment by hisune** [comment]
+1

**Comment by weaigc** [comment]
@hisune @willggy @Cyrus-Reed 不好意思，昨天更新的版本有点小问题，请使用最新版本 0.3.0 再试试

**Comment by weaigc** [comment]
https://github.com/weaigc/bingo/issues/38 @willggy @hisune @Cyrus-Reed
