### ISSUE TITLE
在演示站上提交问题时，显示服务器已被封禁

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#38]
演示站又出现服务器封禁问题了，无论怎样刷新都一样，问题如下:
![Screenshot_20230819_084917](https://github.com/weaigc/bingo/assets/129951996/6cc04793-99da-4432-ba15-f5fb92413042)

**Comment by MiniOcean404** [comment]
+1

**Comment by YMQdadadada** [comment]
+1

**Comment by leilevy** [comment]
+1

**Comment by laiwlong** [comment]
+2

**Comment by yezrun** [comment]
+1

**Comment by Dragoning88** [comment]
+1

**Comment by DyWriteCode** [comment]
+1

**Comment by fjdmt** [comment]
同样，部署在DOCKER上提示被封禁

**Comment by weaigc** [comment]
@Esonyz @fjdmt @leilevy @Dragoning88 @MiniOcean404 接口稳定性问题，一般过段时间重试即可。新版已经把这个错误信息进行了进一步区分
