### ISSUE TITLE
Runtime error Scheduling failure: not enough hardware capacity

### ISSUE THREAD

**Issue by lonevle** [weaigc/bingo#41]
huggingface一键部署出现这个错误.
![image](https://github.com/weaigc/bingo/assets/48077551/b04cb79a-1007-410f-b006-512b9fc762da)

**Comment by 3192575523** [comment]
我也遇到了同样的问题，希望大佬能解决一下

**Comment by lonevle** [comment]
刚试了下又正常了, 看起来像是供应商免费的资源用完了.
