### ISSUE TITLE
发现这个项目被人无耻的售卖

### ISSUE THREAD

**Issue by luckyEason** [weaigc/bingo#45]
https://www.agbgpt.com/web/index.html

![image](https://github.com/weaigc/bingo/assets/109937362/d4a84c6b-5958-4397-8218-bb4d7c455af6)

还卖得不便宜

**Comment by luckyEason** [comment]
还修改源码，删除开源地址

**Comment by luckyEason** [comment]
@weaigc

**Comment by weaigc** [comment]
@luckyEason 这个项目原本的协议是允许别人商用的。我后面想想办法，谢谢反馈。

**Comment by lw1290537863** [comment]
吃不到葡萄说葡萄酸，没有利益驱使，哪有研究动力！既然是允许商用，自然不会留开源地址。建议大佬弄个打赏码，谁商用就得支付点报酬，不然良心被狗吃了

**Comment by luckyEason** [comment]
> 吃不到葡萄说葡萄酸，没有利益驱使，哪有研究动力！既然是允许商用，自然不会留开源地址。建议大佬弄个打赏码，谁商用就得支付点报酬，不然良心被狗吃了

您好，这是Bing。我可以帮您回答关于MIT协议的问题。😊

[MIT协议是一种非常宽松的开源软件许可协议，它只对再使用者提出了非常有限的限制](https://opensource.stackexchange.com/questions/4534/how-to-apply-mit-license-in-the-github-repo-for-fully-free-project)¹。根据MIT协议的条款，再使用者可以自由地复制、修改、合并、发布、分发、再许可或出售软件或软件的副本，只要他们在软件中保留版权和许可声明²。

因此，如果您使用了一个遵循MIT协议的开源项目，您可以删除该项目的开源地址，只要您保留该项目的版权和许可声明。但是，这样做可能会损害您与原始作者和其他贡献者之间的信任和尊重，因为他们可能希望您能够公开地承认他们的工作，并与他们分享您对该项目的改进³。

如果您想了解更多关于MIT协议的信息，您可以参考以下链接：
- [如何在GitHub仓库中应用MIT协议](^[1](https://opensource.stackexchange.com/questions/4534/how-to-apply-mit-license-in-the-github-repo-for-fully-free-project)^)
- [MIT技术许可办公室关于开源许可的建议](^[2](https://tlo.mit.edu/learn-about-intellectual-property/software-and-open-source-licensing/open-source-licensing)^)
- [MIT协议网站](^[3](https://mit-license.org/)^)

希望这些信息对您有所帮助。如果您还有其他问题，请随时提问。😊

源: 与必应的对话， 2023/8/30
(1) How to apply MIT license in the GitHub repo for fully free project?. https://opensource.stackexchange.com/questions/4534/how-to-apply-mit-license-in-the-github-repo-for-fully-free-project.
(2) Open Source Licensing | MIT Technology Licensing Office. https://tlo.mit.edu/learn-about-intellectual-property/software-and-open-source-licensing/open-source-licensing.
(3) MIT License. https://mit-license.org/.
(4) How to apply MIT license in the GitHub repo for fully free project?. https://opensource.stackexchange.com/questions/4534/how-to-apply-mit-license-in-the-github-repo-for-fully-free-project.
(5) Open Source Licensing | MIT Technology Licensing Office. https://tlo.mit.edu/learn-about-intellectual-property/software-and-open-source-licensing/open-source-licensing.
(6) MIT License. https://mit-license.org/.

**Comment by luckyEason** [comment]
> 吃不到葡萄说葡萄酸，没有利益驱使，哪有研究动力！既然是允许商用，自然不会留开源地址。建议大佬弄个打赏码，谁商用就得支付点报酬，不然良心被狗吃了

他必须保留该项目的版权和许可声明，而这个什么爱国版毫无保留的删除了一切有关原作者的信息，还声称是他们公司自主研发的

**Comment by luckyEason** [comment]
> 吃不到葡萄说葡萄酸，没有利益驱使，哪有研究动力！既然是允许商用，自然不会留开源地址。建议大佬弄个打赏码，谁商用就得支付点报酬，不然良心被狗吃了

他必须保留该项目的版权和许可声明，而这个什么爱国版毫无保留的删除了一切有关原作者的信息，还声称是他们公司自主研发的

**Comment by gounahaozi** [comment]
@luckyEason 呦，这么热闹啊。你举报的目的是什么呢？能在这里看到的几乎都是码农。作为同行我看你有红眼病嫌疑，自己的屁股上的屎搽干净了没有呢？开源的项目大家都懂的最终会是怎么回事，你这么气急败坏的行为是为了啥？有几个小白懂我们码农的圈子？

@lw1290537863 兄台一看就是圈内人士，作者辛苦搞出来的项目，同行既然商用，打赏就必不可少，这是规矩！

**Comment by luckyEason** [comment]
@gounahaozi 我还真就没拉屎，也没的什么红眼病，只是是不想

**Comment by weaigc** [comment]
> @gounahaozi 我还真就没拉屎，也没的什么红眼病，只是是不想某个项目被玷污了而已，既然你这么说，不说也罢，我也没闲工夫怼你
> 
> @lw1290537863 说得打赏作者很有道理

暂时还不考虑。现在不太确定封杀力度，如果这个项目半年后还活着的话，再看吧，谢谢大家！
