### ISSUE TITLE
macOS11 Safari14.1浏览器依旧不能运行

### ISSUE THREAD

**Issue by ycp666** [weaigc/bingo#49]
能进入Web页面,但点击发送自己提的问题,就会弹出“Application error: a client-side exception has occurred (see the browser console for more information).”
我看了下javascribe控制台,
Blocked a frame with origin "https://bing.github1s.tk" from accessing a frame with origin "https://hf4all-bingo.hf.space". Protocols, domains, and ports must match.

TypeError: l.at is not a function. (In 'l.at(-1)', 'l.at' is undefined)

Unhandled Promise Rejection: TypeError: t.item.messages.at is not a function. (In 't.item.messages.at(-1)', 't.item.messages.at' is undefined)

**Comment by weaigc** [comment]
> at(-1)

@ycp666 这个确实不兼容 safari 14,你看看能不能用 chrome 或者 safari 15。

**Comment by ycp666** [comment]
>感谢这两个可以

**Comment by weaigc** [comment]
@ycp666 兼容了一下2020左右的浏览器，你再试试？

**Comment by ycp666** [comment]
> @ycp666 兼容了一下2020左右的浏览器，你再试试？

我升级Safari16了,14确实老了,还是不行

**Comment by weaigc** [comment]
@ycp666 我调了一下，现在兼容到2019了，你看看ok了不

**Comment by ycp666** [comment]
> @ycp666 我调了一下，现在兼容到2019了，你看看ok了不

大佬牛逼 可以了
