### ISSUE TITLE
没有获取到身份信息或失败

### ISSUE THREAD

**Issue by nence1** [weaigc/bingo#5]
一键部署到huggingface，输入_U cookie没用，新注册的也不行
[hug链接](https://huggingface.co/spaces/nence/bingoo0)
请教下

**Comment by chenzhiguo** [comment]
附议

**Comment by nence1** [comment]
要用美国的ip重新注册一个新的就可以了，但速度好慢

**Comment by weaigc** [comment]
@nence1 复制的时候请填写一下 BING_COOKIE，hf的话可以随便填，比如 xxx

**Comment by weaigc** [comment]
> 附议

同上
