### ISSUE TITLE
通过cloudflare workers 改域名的方式失效了，配置后打开的页面huggingface提示的404

### ISSUE THREAD

**Issue by Mrycp** [weaigc/bingo#50]

**Comment by boysye** [comment]
现在提示"没有获取到用户信息或用户信息失效，点此重新设置"了

**Comment by weaigc** [comment]
@Mrycp 可以贴一下你的代码吗，https://b.github1s.tk/ 这个是使用 workers 的站点，看起来是正常的。

**Comment by Mrycp** [comment]
找到问题了，是我hf空间设置的问题，设置为私有的了，反代之后就访问不了。改成公开后就可以了。
