### ISSUE TITLE
在演示站中发送问题时，显示未获取用户信息或失效，导致无法正常使用

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#51]
在演示站中，这个问题总是频繁出现，但是我并没有配置用户状态信息，问题如图所示:
![Screenshot_20230831_124932](https://github.com/weaigc/bingo/assets/129951996/c5f9342f-5068-4d51-b7ed-d03ad27a6c18)

**Comment by player868** [comment]
在演示站中，免登录画图功能也出现了同样的问题，此功能似乎只能在下午时间段，才可免登录使用正常画图功能，若是在在其他时间段中使用，也一样出现了未配置用户或无效的问题

**Comment by weaigc** [comment]
> 在演示站中，这个问题总是频繁出现，但是我并没有配置用户状态信息，问题如图所示: ![Screenshot_20230831_124932](https://user-images.githubusercontent.com/129951996/264537675-c5f9342f-5068-4d51-b7ed-d03ad27a6c18.jpg)
@player868 
已修复
