### ISSUE TITLE
在演示站中发送问题时，出现“你已达到每日最大发送消息次数，请更换账号或隔一天后重试”报错

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#52]
在演示站中，当我发送问题时，莫名奇妙的显示已达到每日最大信息发送限制，关键是我并未配置用户信息
![Screenshot_20230831_160057](https://github.com/weaigc/bingo/assets/129951996/8097f12b-545b-4ad0-aac9-a681aa3e1ed1)

**Comment by weaigc** [comment]
@player868 应该是默认账号超过最大次数了，你可以把自己的账号设置进去
