### ISSUE TITLE
feat: 添加Sydney支持

### ISSUE THREAD

**Issue by Happy-clo** [weaigc/bingo#54]
希望作者可以参考[开源项目](https://github.com/danny-avila/LibreChat)添加更聪明的Sydney模型支持 感谢作者从百忙中抽出时间实现此功能

**Comment by weaigc** [comment]
@Happy-clo bing的参数我是用自己的账号对比过的，一些会犯傻的问题官方也是一样会出现。比如 **请帮我 Review 以下代码** 这种问题，问题是偶发，需要多试几次。
你可以看看有没有什么问题是只有 bingo 才会犯傻的，指出来，我分析一下原因

**Comment by Happy-clo** [comment]
好的😊 首先谢谢作者回复 
1.bingo暂未发现与官网不同
2.我的初衷是希望能参考这个项目使本项目体验更好 Sydney目前看是没有bing大小姐的《暴脾气》 毕竟bing都被削惨了

**Comment by weaigc** [comment]
嗯，谢谢
