### ISSUE TITLE
演示站中提交问题时，再次出现未获取用户信息及失效报错，望作者修复

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#58]
这次的报错问题又突然出现了，这次仍然未配置用户，问题如下:
![Screenshot_20230905_111913](https://github.com/weaigc/bingo/assets/129951996/42b3db7c-d7ab-4580-987f-7f069b69baab)

**Comment by zyy1509418342** [comment]
确实，今天用发现有这个问题

**Comment by 3192575523** [comment]
嗯，期待更好的版本

**Comment by weaigc** [comment]
@3192575523 @zyy1509418342 @player868 hf已经被封，目前新方案正在内测中，可能会存在不稳定的问题。

**Comment by coolsf2005** [comment]
已经GG了

**Comment by 3192575523** [comment]
老哥加油
