### ISSUE TITLE
作者的源码的比如标题图片我们不能修改吗

### ISSUE THREAD

**Issue by xiaolin1991** [weaigc/bingo#63]
我的全部是部署到cloudflare的Workers里面,但是发现想修改下标题或者网页的logo都找不到源码的修改地方,好像全部是映射到const TRAGET_HOST='hf4all-bingo.hf.space' // 请将此域名改成你自己的，域名信息在设置》站点域名查看。但是 hf4all-bingo.hf.space  这个网址一更换    #直接整个就打开不了,就想问下项目的这些是不是不能自定义，谢谢, 还有历史记录好像也是没有 所有的菜单都没有找到
[worker.zip](https://github.com/weaigc/bingo/files/12554832/worker.zip)

**Comment by Propny** [comment]
我也遇到相同情况

**Comment by Happy-clo** [comment]
本质上是可以的 你需要自己在这个项目中创建一个分支 然后修改这个项目的源代码 并自己打Docker镜像 在hf部署的Dockerfile换成你自己的Docker镜像地址就可以了

**Comment by Happy-clo** [comment]
然后将cf的地址换成你自己的项目地址就可以了

**Comment by weaigc** [comment]
@xiaolin1991 @Propny 代码在这 https://github.com/weaigc/bingo/blob/main/src/app/layout.tsx

**Comment by weaigc** [comment]
> 
@xiaolin1991 @Propny 
workers不是主站源码，你可能理解错了，那个是可以可无的
