### ISSUE TITLE
在演示站提交信息时，显示用户信息未获取或失效报错

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#67]
报错情况如图:
![Screenshot_20230913_064909](https://github.com/weaigc/bingo/assets/129951996/30042bb0-ec2e-44b7-9e64-8e5901199df2)

**Comment by weaigc** [comment]
@player868 需要登录了，免账号基本上不能用了

**Comment by SokWith** [comment]
> @player868 需要登录了，免账号基本上不能用了

通过刷新MUID值，可以实现免账户使用10次会话。所以，建议每次刷新都换MUID值。

**Comment by weaigc** [comment]
@player868 https://github.com/weaigc/bingo/issues/74
