### ISSUE TITLE
图片输入功能不可用

### ISSUE THREAD

**Issue by renqabs** [weaigc/bingo#7]
没添加图片上传功能是因为EdgeGPT没有这个功能吗，如果需要的话，我这有个修改版的edgeGPT，实现了图片上传功能，大佬可以参考下，https://github.com/SoraRoseous/ChatSydney-react.git

**Comment by weaigc** [comment]
> 没添加图片上传功能是因为EdgeGPT没有这个功能吗，如果需要的话，我这有个修改版的edgeGPT，实现了图片上传功能，大佬可以参考下，https://github.com/SoraRoseous/ChatSydney-react.git

有图片功能的，只不过需要你配置了cookie才能使用，这是相关代码 https://github.com/weaigc/bingo/blob/main/src/pages/api/image.ts

**Comment by renqabs** [comment]
> > 没添加图片上传功能是因为EdgeGPT没有这个功能吗，如果需要的话，我这有个修改版的edgeGPT，实现了图片上传功能，大佬可以参考下，https://github.com/SoraRoseous/ChatSydney-react.git
> > @renqabs
> > 有图片功能的，只不过需要你配置了cookie才能使用，这是相关代码 https://github.com/weaigc/bingo/blob/main/src/pages/api/image.ts

但是上传图片可以不用cookie的呀，我给你的那个项目就是

**Comment by weaigc** [comment]
> > > 没添加图片上传功能是因为EdgeGPT没有这个功能吗，如果需要的话，我这有个修改版的edgeGPT，实现了图片上传功能，大佬可以参考下，https://github.com/SoraRoseous/ChatSydney-react.git
> > > @renqabs
> > > 有图片功能的，只不过需要你配置了cookie才能使用，这是相关代码 https://github.com/weaigc/bingo/blob/main/src/pages/api/image.ts
> 
> 但是上传图片可以不用cookie的呀，我给你的那个项目就是，我指的是图片输入，不是图片输出，这个样子的 ![image](https://user-images.githubusercontent.com/130155002/256548991-ce994797-d8fb-4f6d-b7c7-033e030a397f.png)

哦哦，这个功能我这两天加一下，稍等

**Comment by renqabs** [comment]
> > > > 没添加图片上传功能是因为EdgeGPT没有这个功能吗，如果需要的话，我这有个修改版的edgeGPT，实现了图片上传功能，大佬可以参考下，https://github.com/SoraRoseous/ChatSydney-react.git
> > > > @renqabs
> > > > 有图片功能的，只不过需要你配置了cookie才能使用，这是相关代码 https://github.com/weaigc/bingo/blob/main/src/pages/api/image.ts
> > 
> > 
> > 但是上传图片可以不用cookie的呀，我给你的那个项目就是，我指的是图片输入，不是图片输出，这个样子的 ![image](https://user-images.githubusercontent.com/130155002/256548991-ce994797-d8fb-4f6d-b7c7-033e030a397f.png)
> 
> 哦哦，这个功能我这两天加一下，稍等

好的，感谢大佬

**Comment by weaigc** [comment]
@renqabs 已发布
