### ISSUE TITLE
在演示站中，用户信息未获取或失效报错频繁出现，这个问题提交过了很多次，虽然经过了作者多次有效修复后，但BUG至今任然还在出现

### ISSUE THREAD

**Issue by player868** [weaigc/bingo#70]
![Screenshot_20230916_183255](https://github.com/weaigc/bingo/assets/129951996/c50fa214-2247-4173-891d-d1461e48332a)
![Screenshot_20230916_183341](https://github.com/weaigc/bingo/assets/129951996/d7e61bc0-192f-4f25-9336-2be53d246394)

**Comment by player868** [comment]
求求作者修好这个Bug吧！这种报错已经出现过很多次了，修了没多久又开始出现这样的报错

**Comment by SokWith** [comment]
https://github.com/weaigc/bingo/issues/69#issuecomment-1722149902

**Comment by weaigc** [comment]
@player868 https://github.com/weaigc/bingo/issues/74
