### ISSUE TITLE
想要访问时不用设置就可以用

### ISSUE THREAD

**Issue by wjsw3369** [weaigc/bingo#72]
在抱脸克隆部署(0.8.0)，已经在Dockerfile里设置了BING_HEADER和BING_COOKIE的值，是自己的账户的Challenge转的，填上Challenge一直都可以使用，但不填有时候就不能用，但有时候也可以用

**Comment by wjsw3369** [comment]
昨天不可用时，也在设置中多次尝试"Factory reboot"，也还是不能用，今天却可以了

**Comment by wjsw3369** [comment]
设置了这两个参数也不行吗，就必须填访问界面填Challenge值吗

**Comment by wjsw3369** [comment]
有时候填上Challenge也无法使用，Like now.

**Comment by weaigc** [comment]
@wjsw3369 https://github.com/weaigc/bingo/issues/74
