### ISSUE TITLE
增加对话次数

### ISSUE THREAD

**Issue by wjsw3369** [weaigc/bingo#75]
希望可以增加单次对话的次数

**Comment by lwdgit** [comment]
> 希望可以增加单次对话的次数
@wjsw3369 
把你的身份信息填进去就有30次，不登录的话就是10次。这个是官方的限制

**Comment by wjsw3369** [comment]
> > 希望可以增加单次对话的次数
>  @wjsw3369
>  把你的身份信息填进去就有30次，不登录的话就是10次。这个是官方的限制

@lwdgit
我填入了，但仍只有10次，而且这几天一到下午和晚上就没法用了，就像现在；提示"请求次数过快，已被限流，请稍候重试..."，无论填写信息与否都是，演示站也一样，第二天上午又可以正常对话

**Comment by weaigc** [comment]
@wjsw3369 bing.github1s.tk目前不支持自定义身份信息，如果需要请自己找个干净的机器搭建。
![image](https://github.com/weaigc/bingo/assets/39235693/17790547-9d6a-44e0-9b59-7e704e92c7b9)
