### ISSUE TITLE
请求openai方式调用增加识图功能调用

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [weaigc/bingo#83]
如题,请求可以仅仅把这个api开放给本地部署的服务器我自行部署,十分需要,非常感谢!

**Comment by weaigc** [comment]
> 如题,请求可以仅仅把这个api开放给本地部署的服务器我自行部署,十分需要,非常感谢!

@systemoutprintlnhelloworld 没看到官方文档有提供识图api呀，可以给个文档吗

**Comment by systemoutprintlnhelloworld** [comment]
文档中应该是没有的😂我以为站内方法都是大大实现的.
我在站内调用网站识图功能的对话发现请求中会比文本对话对一行图像地址参数,请问可以用websocket模拟浏览器对网站发送请求实现自动化吗
![image](https://github.com/weaigc/bingo/assets/62531937/72cf7bdd-84bd-4488-a303-b811443704a3)
**VQA**
![image](https://github.com/weaigc/bingo/assets/62531937/c1af7e73-e593-4474-a1a4-817bac316b71)
**QA**

缺点是clientId,conversationId不知道如何获取(conversationId应该十次对话结束就重置?),另外如果只能识别上传到bing的图的话,图片上传也是个问题

**Comment by weaigc** [comment]
> 文档中应该是没有的😂我以为站内方法都是大大实现的. 我在站内调用网站识图功能的对话发现请求中会比文本对话对一行图像地址参数,请问可以用websocket模拟浏览器对网站发送请求实现自动化吗 ![image](https://user-images.githubusercontent.com/62531937/276970204-72cf7bdd-84bd-4488-a303-b811443704a3.png) **VQA** ![image](https://user-images.githubusercontent.com/62531937/276971641-c1af7e73-e593-4474-a1a4-817bac316b71.png) **QA**
> 
> 缺点是clientId,conversationId不知道如何获取(conversationId应该十次对话结束就重置?),另外如果只能识别上传到bing的图的话,图片上传也是个问题

我要遵守openai的规范，不然做出来也没几个人会用。等有简单的使用方式我再考虑吧。如果真想用，你可以自己封装一个
