### ISSUE TITLE
突然强制录入身份信息

### ISSUE THREAD

**Issue by huahuakan** [weaigc/bingo#84]
大佬你这个我前几天用都好好的可以直接用，今天突然就一直报用户信息获取失败，怎么现在一定要信息才能用了吗

**Comment by daerbiubiu** [comment]
我也是

**Comment by huahuakan** [comment]
还变成这样了
![图片](https://github.com/weaigc/bingo/assets/148333068/9265e988-8613-40b3-bf52-f5663ceda9bf)

**Comment by weaigc** [comment]
> 大佬你这个我前几天用都好好的可以直接用，今天突然就一直报用户信息获取失败，怎么现在一定要信息才能用了吗
@daerbiubiu @huahuakan 
已恢复

**Comment by huahuakan** [comment]
> > 大佬你这个我前几天用都好好的可以直接用，今天突然就一直报用户信息获取失败，怎么现在一定要信息才能用了吗
> > @daerbiubiu @huahuakan
> > 已恢复

好耶！(≧∇≦)ﾉ
