### ISSUE TITLE
终端请求api报错 Internal Server Error

### ISSUE THREAD

**Issue by jingliancui** [weaigc/bingo#89]
```
ericcui@ericdeMacBook-Pro ~ % curl -kL 'https://copilot.github1s.tk/api/v1/chat/completions' \
  -H 'Content-Type: application/json' \
  -d '{
    "messages":[{"role":"user","content":"你好"}],
    "stream":true,
    "model":"Creative"
  }' \
--compressed
Internal Server Error%
```

**Comment by weaigc** [comment]
> ```
> ericcui@ericdeMacBook-Pro ~ % curl -kL 'https://copilot.github1s.tk/api/v1/chat/completions' \
>   -H 'Content-Type: application/json' \
>   -d '{
>     "messages":[{"role":"user","content":"你好"}],
>     "stream":true,
>     "model":"Creative"
>   }' \
> --compressed
> Internal Server Error%
> ```
重试
