### ISSUE TITLE
第二个演示站点会要求登录，但是登录后会显示内部错误，自己部署到vercel设置环境变量也是现实内部错误

### ISSUE THREAD

**Issue by ysmzxc** [weaigc/bingo#9]
BING_UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.0.0'
BING_IP=11.123.111.2
BING_COOKIE='bing.com 名为 _U 的 Cookie 值'
我按照这个设置了环境变量

**Comment by weaigc** [comment]
@ysmzxc https://github.com/weaigc/bingo/issues/10
