### ISSUE TITLE
V2不能支持api了吗

### ISSUE THREAD

**Issue by mycurjerry** [weaigc/bingo#90]
https://bing.github1s.tk/api 好像不存在。作者会继续开放api吗？毕竟有api可以用很多类似chatbox的桌面应用，很方便

**Comment by weaigc** [comment]
> https://bing.github1s.tk/api 好像不存在。作者会继续开放api吗？毕竟有api可以用很多类似chatbox的桌面应用，很方便

用 copilot.github1s.tk
