### ISSUE TITLE
能否把“cookie仅用于画图”这个功能再加回来

### ISSUE THREAD

**Issue by renqabs** [weaigc/bingo#92]
突破bingai限制，可能有封号的风险，仅在画图时使用cookie应该可以降低一些风险

**Comment by weaigc** [comment]
> 突破bingai限制，可能有封号的风险，仅在画图时使用cookie应该可以降低一些风险

这个功能一直都在，只不过后面改名了，叫 “尝试修复用户信息异常”

**Comment by renqabs** [comment]
> > 突破bingai限制，可能有封号的风险，仅在画图时使用cookie应该可以降低一些风险
> 
> 这个功能一直都在，只不过后面改名了，叫 “尝试修复用户信息异常”

好的，感谢大佬解惑
