### ISSUE TITLE
建议支持插件系统

### ISSUE THREAD

**Issue by jsdianman** [weaigc/bingo#93]
官网已开放插件系统的使用，并且支持禁用搜索

**Comment by lwdgit** [comment]
> 官网已开放插件系统的使用，并且支持禁用搜索

@jsdianman 插件系统还在AB测试中，我这边还没有。暂时没办法分析插件是怎么工作的，网上也没有相关文章，不太好做适配

**Comment by boool369** [comment]
请问如何开启不联网模式？

**Comment by Happy-clo** [comment]
@boool369  好像只是api调用 网页端早已支持

**Comment by weaigc** [comment]
> 请问如何开启不联网模式？

网页端使用的话启用Gpt4模式，api使用model指定为gpt-4
