### ISSUE TITLE
不登陆似乎无法使用了，总是报错”请求失败，请手动重试“

### ISSUE THREAD

**Issue by StoneLyu** [weaigc/bingo#95]
MS最近更新了MS Copilot，不知道是不是这个原因导致不登录的情况下无法正常使用了。
我尝试了MS Copilot了，不像new bing那样封得特别死，应该就是IP能访问就行了。

**Comment by SokWith** [comment]
https://github.com/weaigc/bingo/issues/78#issuecomment-1815749659
自建两个后台服务器来解决，效果见我的测试域 https://nbing.eu.org

**Comment by weaigc** [comment]
已修复
