### ISSUE TITLE
能否自定义聊天接入点 

### ISSUE THREAD

**Issue by Nothingness-Void** [weaigc/bingo#99]
如题 我用[另一个项目](https://github.com/adams549659584/go-proxy-bingai)在微软Az的机器上成功搭建了bing的镜像站（不登陆也能用） 但同一机器搭建本项目却无法使用， 该项目无法使用API调用 想问一下本项目是否能添加调用其他的bing接入点的功能 如图：
![image](https://github.com/weaigc/bingo/assets/55913486/6652be1f-1e07-4331-bc3f-a9fcb37ee7ec)

**Comment by SokWith** [comment]
我之前问过大佬，替他回答了吧：

环境变量 ENDPOINT  =  "www.bing.com"
环境变量  WS_ENDPOINT = "sydney.bing.com"

隔壁项目的部署既可以当 ENDPOINT ， 也可以当 WS_ENDPOINT；

**Comment by Nothingness-Void** [comment]
> 我之前问过大佬，替他回答了吧：
> 
> 环境变量 ENDPOINT = "www.bing.com" 环境变量 WS_ENDPOINT = "sydney.bing.com"
> 
> 隔壁项目的部署既可以当 ENDPOINT ， 也可以当 WS_ENDPOINT；
> 
> 现在主要是WS的行为控制非常厉害，我让bing写的wss反代服务部署在render上，一个地区的站点存活比较正常，另外一个地区的半天就被锁了。

感谢大佬解惑

**Comment by SokWith** [comment]
https://github.com/weaigc/bingo/issues/78#issuecomment-1829350889
